resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/9.yaml

allow-newer: true

packages:
- .

extra-deps:
- regex-posix-clib-2.7

flags:
   regex-posix:
      _regex-posix-clib: true